version: '3'
services:

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env.local
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
      - "5432:5432"  # чтобы при отладке использовать на хосте менеджеры БД (например pgAdmin)
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME_PG}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  es:
    image: elasticsearch:8.6.2
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    ports:
      - "9200:9200"  # чтобы можно было законнетиться, например, Postman ом из хоста

  etl:
    build: ./postgres_to_es
    container_name: etl
    env_file:
      - .env.local
