version: '3'
services:

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env.local
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  es:
    image: elasticsearch:8.6.2
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  etl:
    build: ./postgres_to_es
    container_name: etl
    env_file:
      - ./postgres_to_es/.env.prod
