[tool.poetry]
name = "async-api-sprint-1"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "async_api_sprint_1"}]

[tool.poetry.dependencies]
python = "^3.10"
redis = "4.4.2"
elasticsearch = {version = "7.9.1", extras = ["async"]}
fastapi = "0.61.1"
orjson = "^3.9.2"
pydantic = "1.9.0"
uvicorn = "0.12.2"
uvloop = {version = "0.17.0", markers = 'sys_platform != "win32" and implementation_name == "cpython"'}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
